site_name: Mobile Development Environment Setup
site_description: Professional guide for establishing a complete mobile development environment using Claude Code
site_author: Mobile Development Environment Setup
site_url: https://valdres.github.io/mobile-vibe-coding/

repo_name: valdres/mobile-vibe-coding
repo_url: https://github.com/valdres/mobile-vibe-coding

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Setup Guide:
    - iOS SSH Configuration: setup/ios-ssh.md
    - iOS Code Editors: setup/ios-editors.md
    - VPS Configuration: setup/vps.md
    - Development Environment: setup/dev-env.md
    - Nix with Determinate Systems: setup/nix-determinate.md
    - Cloud-Init Automation: setup/cloud-init.md
    - Port Forwarding: setup/port-forwarding.md
  - Support:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
  - References: references.md